# Generated by Django 6.0.1 on 2026-01-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='package',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Access rank. Higher number = higher access'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='What this package offers'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to stop new subscriptions'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text='e.g. Ordinary, VIP, VVIP, hub', max_length=50, unique=True),
        ),
    ]
